/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_italo_italonet_ItalonetVPN_VPNInfo */

#ifndef _Included_network_italo_italonet_ItalonetVPN_VPNInfo
#define _Included_network_italo_italonet_ItalonetVPN_VPNInfo
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef __cplusplus
}
#endif
#endif
