/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_italo_italonet_ItalonetDaemon */

#ifndef _Included_network_italo_italonet_ItalonetDaemon
#define _Included_network_italo_italonet_ItalonetDaemon
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_italo_italonet_ItalonetDaemon
   * Method:    Obtain
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_italo_italonet_ItalonetDaemon_Obtain(JNIEnv*, jclass);

  /*
   * Class:     network_italo_italonet_ItalonetDaemon
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_italo_italonet_ItalonetDaemon_Free(JNIEnv*, jclass, jobject);

  /*
   * Class:     network_italo_italonet_ItalonetDaemon
   * Method:    Configure
   * Signature: (Lnetwork/italo/italonet/ItalonetConfig;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_italo_italonet_ItalonetDaemon_Configure(JNIEnv*, jobject, jobject);

  /*
   * Class:     network_italo_italonet_ItalonetDaemon
   * Method:    Mainloop
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_italo_italonet_ItalonetDaemon_Mainloop(JNIEnv*, jobject);

  /*
   * Class:     network_italo_italonet_ItalonetDaemon
   * Method:    IsRunning
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_italo_italonet_ItalonetDaemon_IsRunning(JNIEnv*, jobject);

  /*
   * Class:     network_italo_italonet_ItalonetDaemon
   * Method:    Stop
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_italo_italonet_ItalonetDaemon_Stop(JNIEnv*, jobject);

  /*
   * Class:     network_italo_italonet_ItalonetDaemon
   * Method:    InjectVPN
   * Signature: (Lnetwork/italo/italonet/ItalonetVPN;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_italo_italonet_ItalonetDaemon_InjectVPN(JNIEnv*, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
