/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_italo_italonet_ItalonetVPN */

#ifndef _Included_network_italo_italonet_ItalonetVPN
#define _Included_network_italo_italonet_ItalonetVPN
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_italo_italonet_ItalonetVPN
   * Method:    PacketSize
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_italo_italonet_ItalonetVPN_PacketSize(JNIEnv*, jclass);

  /*
   * Class:     network_italo_italonet_ItalonetVPN
   * Method:    Alloc
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_italo_italonet_ItalonetVPN_Alloc(JNIEnv*, jclass);

  /*
   * Class:     network_italo_italonet_ItalonetVPN
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_italo_italonet_ItalonetVPN_Free(JNIEnv*, jclass, jobject);

  /*
   * Class:     network_italo_italonet_ItalonetVPN
   * Method:    Stop
   * Signature: ()V
   */
  JNIEXPORT void JNICALL
  Java_network_italo_italonet_ItalonetVPN_Stop(JNIEnv*, jobject);

  /*
   * Class:     network_italo_italonet_ItalonetVPN
   * Method:    ReadPkt
   * Signature: (Ljava/nio/ByteBuffer;)I
   */
  JNIEXPORT jint JNICALL
  Java_network_italo_italonet_ItalonetVPN_ReadPkt(JNIEnv*, jobject, jobject);

  /*
   * Class:     network_italo_italonet_ItalonetVPN
   * Method:    WritePkt
   * Signature: (Ljava/nio/ByteBuffer;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_italo_italonet_ItalonetVPN_WritePkt(JNIEnv*, jobject, jobject);

  /*
   * Class:     network_italo_italonet_ItalonetVPN
   * Method:    SetInfo
   * Signature: (Lnetwork/italo/italonet/ItalonetVPN/VPNInfo;)V
   */
  JNIEXPORT void JNICALL
  Java_network_italo_italonet_ItalonetVPN_SetInfo(JNIEnv*, jobject, jobject);
#ifdef __cplusplus
}
#endif
#endif
