#!/bin/sh -e
setcap cap_net_admin,cap_net_bind_service=+eip /usr/bin/italonet || echo "failed to setcap italonet"
adduser --quiet --system --home /var/lib/italonet debian-italonet || echo "debian-italonet user not added"
