#!/bin/sh

PERMS_OWNER=root
PERMS_GROUP=admin
CHOWN=$PERMS_OWNER:$PERMS_GROUP

# set up italonet data dir
[ -e /var/lib/italonet/ ] || mkdir /var/lib/italonet 
chown $CHOWN /var/lib/italonet
chmod g+w /var/lib/italonet

# mv files copied into $INSTALL_PREFIX/extra/ to their proper locations
mv /opt/italonet/extra/italonet_macos_daemon_script.sh /var/lib/italonet
chown $CHOWN /var/lib/italonet/italonet_macos_daemon_script.sh
chmod 770 /var/lib/italonet/italonet_macos_daemon_script.sh

mv /opt/italonet/extra/network.italo.italonet.daemon.plist /Library/LaunchDaemons/
chown $CHOWN /Library/LaunchDaemons/network.italo.italonet.daemon.plist
chmod 640 /Library/LaunchDaemons/network.italo.italonet.daemon.plist

# clean up by removing 'extra/' (so long as it's empty)
rmdir /opt/italonet/extra/

# bootstrap
/opt/italonet/bin/italonet-bootstrap mainnet /var/lib/italonet/bootstrap.signed
chown $CHOWN /var/lib/italonet/bootstrap.signed

# generate configs
/opt/italonet/bin/italonet -g /var/lib/italonet/italonet.ini
chown $CHOWN /var/lib/italonet/italonet.ini

# register with launchd and start
launchctl load /Library/LaunchDaemons/network.italo.italonet.daemon.plist
launchctl start network.italo.italonet.daemon
