#ifndef LLARP_DEFAULTS_HPP
#define LLARP_DEFAULTS_HPP

#ifndef DEFAULT_RESOLVER_US
#define DEFAULT_RESOLVER_US "1.1.1.1"
#endif
#ifndef DEFAULT_RESOLVER_EU
#define DEFAULT_RESOLVER_EU "1.1.1.1"
#endif
#ifndef DEFAULT_RESOLVER_AU
#define DEFAULT_RESOLVER_AU "1.1.1.1"
#endif

#ifndef DEFAULT_ITALONET_USER
#define DEFAULT_ITALONET_USER "italonet"
#endif
#ifndef DEFAULT_ITALONET_GROUP
#define DEFAULT_ITALONET_GROUP "italonet"
#endif

#endif
